"""Frozen protocol constants for the topic-matched Reddit–LLM experiment."""

TOKENIZER_NAME = "cl100k_base"
EMBEDDING_MODEL = "text-embedding-3-large"
REFEREE_MODEL = "gpt-4o-mini"

N_AGENTS = 3
TEMPERATURE = 0.9
MAX_TOKENS_PER_GENERATION = 200
SHORT_TERM_MEMORY_ROUNDS = 3
RAG_TOKEN_BUDGET = 5000
CONTINUATION_TOKENS = 20_000
SIMULATION_SEED = 20260817

CHUNK_TOKENS = 100
CHUNKS_PER_WINDOW = 20
WINDOW_TOKENS = CHUNK_TOKENS * CHUNKS_PER_WINDOW
WINDOWS_PER_TRAJECTORY = CONTINUATION_TOKENS // WINDOW_TOKENS

EARLY_WINDOWS = (1, 2, 3)
LATE_WINDOWS = (8, 9, 10)

BOOTSTRAP_DRAWS = 10_000
BOOTSTRAP_SEED = 42
